ingest:
  - source: 'pdf'
    source_path: '/Users/ashwin.gangadhar/demo/maap-chatbot-builder/builder/partnerproduct/data/travel-policy.pdf'
    chunk_size: 2000
    chunk_overlap: 200
embedding:
    class_name: Azure-OpenAI-Embeddings
    model_name: 'text-embedding-ada-002' 
    deployment_name: "leafy-embedding-ada-002"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"

vector_store:
    connectionString: 'mongodb+srv://admin:test123@demo.fmxyq.mongodb.net/'
    dbName: 'chatter'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    vectorSearchIndexName: 'vector_index'
    numCandidates: 150
    minScore: 0.1 
    similarityFunction: 'cosine'
llms:
    class_name: AzureOpenAI
    deployment_name: "leafyhosp-gpt-35-turbo"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"
    temprature: ''
stream_options:
    stream: true
aggregate_operators:
    - connectionString: mongodb+srv://ashwinprsnl:p5w6ash@cflt-demo.2wqno.mongodb.net/?retryWrites=true&w=majority&appName=CFLT-demo'
      dbName: test
      collectionName: test
      aggregatePipelineName: testing
      query: [{"$match": {"$or": [{"fistName": "<first_Name>"}, {"lastName": "<last_name>"}]}}]

conditional_operators:
    - name: 'lnfn'
      description: 'given last name and fist name fetch message'
      prompt: "`Convert natural langugage query to MongoDB aggregation / MQL query given the the template for query : ${mqlQuery} \n Instruction=Replace or fill in the variables in query that is represented as enclosed <_>`"
      aggregatePipelineName: 'testing'