ingest:
    - source: 'web'
      source_path: 'https://mongodb-partners.github.io/maap-chatbot-builder/docs/intro'
      chunk_size: 1000
      chunk_overlap: 100
    
embedding:
    class_name: "Azure-OpenAI-Embeddings"
    model_name: 'text-embedding-ada-002' 
    deployment_name: "leafy-embedding-ada-002"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"

vector_store:
    connectionString: 'mongodb+srv://admin:test123@demo.fmxyq.mongodb.net/'
    dbName: 'chatter'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    vectorSearchIndexName: 'vector_index'
    numCandidates: 150
    minScore: 0.1 
    similarityFunction: 'cosine'
llms:
    class_name: AzureOpenAI
    deployment_name: "leafyhosp-gpt-35-turbo"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"
    temprature: ''

stream_options:
    stream: true
aggregate_operators:
    - connectionString: "mongodb+srv://ashwinprsnl:p5w6ash@cflt-demo.2wqno.mongodb.net/?retryWrites=true&w=majority&appName=CFLT-demo"
      dbName: test
      collectionName: test
      aggregatePipelineName: testing
      query: [{"$match": {"$or": [{"fistName": "<first_Name>"}]}}]
      queryFilePath: '/your-file-path'
conditional_operators:
    - name: 'lnfn'
      description: 'given last name and fist name fetch message'
      prompt: "`Given : ${mqlQuery}, replace the <> values with the actual values from the natual language query.
                For example, QueryTemplate: [{'$match': {'firstName': <first_name>}}]
                User query: fetch the message for John Doe
                Result Query: [{'$match': {'firstName': 'John'}}]`"
      promptFilePath: '/your-file-path'
      aggregatePipelineName: 'testing'