ingest:
  # - source: 'pdf'
  #   source_path: '/Users/rahulbatta/Downloads/The-SAT-April-13-19-2024-E-paper-compressed.pdf'
  #   chunk_size: 2000
  #   chunk_overlap: 200
    - source: 'folder'
      file_type: 'pdf'
      source_path: '/Users/utsavtalwar/Desktop/MBA/Mtech'
      chunk_size: 1000
      chunk_overlap: 100
embedding:
    class_name: Fireworks
    model_name: 'nomic-ai/nomic-embed-text-v1.5'
vector_store:
    connectionString: 'mongodb+srv://admin:test123@demo.fmxyq.mongodb.net/'
    dbName: 'SA_Times2'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    numCandidates: 150
    minScore: 0.6
    vectorSearchIndexName: 'vector_index'
llms: job
    class_name: Fireworks
    model_name: 'accounts/fireworks/models/mixtral-8x22b-instruct'