ingest:
  - source: 'pdf'
    source_path: '/Users/ashwin.gangadhar/demo/maap-chatbot-builder/builder/partnerproduct/data/travel-policy.pdf'
    chunk_size: 2000
    chunk_overlap: 200
embedding:
    class_name: Nomic-v1.5
vector_store:
    connectionString: 'mongodb+srv://ashwinprsnl:p5w6ash@cflt-demo.2wqno.mongodb.net/?retryWrites=true&w=majority&appName=CFLT-demo'
    dbName: 'travel_insurance_policy'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    numCandidates: 150
    minScore: 0.1 
    vectorSearchIndexName: 'vector_index'
llms:
    class_name: Fireworks
    model_name: 'accounts/fireworks/models/mixtral-8x22b-instruct'
    temprature: ''
    top_p: ''
    top_k: ''
stream_options:
    stream: true
aggregate_operators:
    - connectionString: mongodb+srv://ashwinprsnl:p5w6ash@cflt-demo.2wqno.mongodb.net/?retryWrites=true&w=majority&appName=CFLT-demo'
      dbName: test
      collectionName: test
      aggregatePipelineName: testing
      query: [{"$match": {"$or": [{"fistName": "<first_Name>"}, {"lastName": "<last_name>"}]}}]

conditional_operators:
    - name: 'lnfn'
      description: 'given last name and fist name fetch message'
      prompt: "`Convert natural langugage query to MongoDB aggregation / MQL query given the the template for query : ${mqlQuery} \n Instruction=Replace or fill in the variables in query that is represented as enclosed <_>`"
      aggregatePipelineName: 'testing'

