ingest:
    source: 'web'
    source_path: 'https://www.careinsurance.com/sitemap.xml'
embedding:
    top_k: ''
    class_name: OpenAIEmbeddings
    model_name: text-embedding-ada-002
vector_store:
    connectionString: '********'
    dbName: 'EMBEDJS'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    vectorSearchIndexName: 'vector_index'
llms:
    class_name: Fireworks
    model_name: ''
    temprature: ''
    top_p: ''
    top_k: ''
rag_pipeline:
    - vs: ''
      embedding: embedding
    - retriver:
          class_name: multiqueryretriver
          vs: vs
          llm: llm
    - chat_engine: llm
ingest_pipeline: []
